stages:
  - build
  - test
  - build-package
  - merge-request
  - artifacts-deploy

image: maven:3.9.2-eclipse-temurin-17

cache:
  paths:
    - .m2/repository
  key: ${CI_COMMIT_SHA}

build-job:
  stage: build
  tags: [linux, docker]
  script:
    - mvn clean verify -DskipTests

artifacts-deploy:
  stage: artifacts-deploy
  script:
    - mvn clean package -DskipTests
  artifacts:
    paths: 
      - $CI_PROJECT_DIR/docs

build-package:
  stage: build-package
  when: manual

  script:
    - mvn clean package

test-job:
  only: 
    - dev
  stage: test
  script:
    - mvn test

merge-request:
  stage: merge-request
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  script:
    - mvn clean verify