stages:
  - build
  # - build-image
  - docker-build

image: maven:3.9.2-eclipse-temurin-17

build-job:
  stage: build
  tags: [linux, shared]
  script:
    - mvn clean verify

# build-image:
#   stage: build-image
#   tags: [linux, shared]
#   script:
#     - mvn clean spring-boot:build-image

build:
  image: docker:20.10.16
  stage: docker-build
  services:
    - docker:20.10.16-dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY/group/project/image:latest .
    - docker push $CI_REGISTRY/group/project/image:latest