stages:
  - build
  - test

image: maven:3.9.2-eclipse-temurin-17

build-job:
  stage: build
  tags: [linux, docker]
  script:
    - mvn clean verify -DskipTests

test-job:
  only: 
    - dev
  stage: test
  script:
    - mvn test