stages:
  - build
  - test

image: openjdk:17.0.2-slim-bullseye

build-job:
  stage: build
  tags: [docker]
  script:
    - mvn clean verify -DskipTests

test-job:
  stage: test
  script:
    - mvn test